(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const c=[{surname:"Clements",nameA:"Golden",patronymic:"GG",dob:24},{surname:"Hebert",nameA:"Francis",patronymic:"FF",dob:24},{surname:"Cross",nameA:"Hale",patronymic:"LL",dob:24}];let l=document.querySelector("#authorList"),p=document.querySelector("#saveButton"),u=null,y=document.querySelector("#output");y.addEventListener("submit",b);function b(e){e.preventDefault();const t=new FormData(e.currentTarget);console.log(t);let o=Object.fromEntries(t.entries());console.log(o);const s=a=>{const{surname:i,nameA:m,patronymic:d,dob:f}=a;return`
  <tr>
    <td>${i}</td>
    <td>${m}</td>
    <td>${d}</td>
    <td>${f}</td>     
  </tr>
  `};console.log(o);const r=document.querySelector(".authors-table"),n=o.map(s).join("");r.insertAdjacentHTML("beforeend",n)}for(let e=0;e<c.length;e++){const t=c[e];let o=document.createElement("li");o.textContent=t.surname+" "+t.nameA,o.dataset.authorNumber=e,l.append(o)}l.addEventListener("click",function(e){e.target.tagName=="LI"&&(u=c[e.target.dataset.authorNumber],v(u),g(e.target))});p.addEventListener("click",function(){h(u)});function g(e){L(),e.classList.add("selected")}function L(){let e=document.querySelectorAll("li.selected");for(let t=0;t<e.length;t++)e[t].classList.remove("selected")}function v(e){const t=document.forms[0];t.surname.value=e.surname,t.nameA.value=e.nameA,t.patronymic.value=e.patronymic,t.dob.value=e.dob}function h(e){const t=document.forms[0];e.surname=t.surname.value,e.nameA=t.nameA.value,e.patronymic=t.patronymic.value,e.dob=t.dob.value}
//# sourceMappingURL=page-2.js.map
