/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();let p=document.querySelector("#input-author"),h=document.querySelector("#input");document.querySelector("#output");document.querySelector("#book");let g=document.querySelector(".books"),y=document.querySelector(".authors"),s=[],d=[];p.addEventListener("submit",b);h.addEventListener("submit",L);function b(r){r.preventDefault();const t=new FormData(r.currentTarget);console.log(t);let n=Object.fromEntries(t.entries());console.log(n),s.push(n),console.log(s),localStorage.setItem("author",JSON.stringify(s)),y.innerHTML=`<table class="record-author"> 
  <thead class="recd-auth">
    <tr>
      <th data-type="string">Автори</th>
      <th data-type="number">Книг в базе</th>
    </tr>
    </thead>
    <tbody class="rec-auth"></tbody>
    </table>`,E(s);let l=document.querySelector(".record-author");console.log(l),l.onclick=function(o){if(o.target.tagName!="TH")return;let c=o.target;e(c.cellIndex,c.dataset.type)};function e(o,c){let m=l.querySelector("tbody"),f=Array.from(m.rows),a;switch(c){case"number":a=function(u,i){return u.cells[o].innerHTML-i.cells[o].innerHTML};break;case"string":a=function(u,i){return u.cells[o].innerHTML>i.cells[o].innerHTML?1:-1};break}f.sort(a),m.append(...f)}}function E(r){console.log(r);for(let t=0;t<r.length;t++){let n=document.createElement("tr");n.id="text",n.className="note",console.log(n),n.innerHTML=`    
    <td>${r[t].initials}</td>
    <td>${r[t].collection}</td>            
    <input name="del-auth" type="button" value="видалити"/>`,document.querySelector(".rec-auth").appendChild(n);let l=document.getElementsByName("del-auth");console.log(l),l.forEach(function(e){console.log(e),e.addEventListener("click",function(){console.log(e),e.parentNode.parentNode.removeChild(e.parentNode)})}),document.getElementById("initials").value=" ",document.getElementById("collection").value="0"}}function L(r){r.preventDefault();const t=new FormData(r.currentTarget);console.log(t);let n=Object.fromEntries(t.entries());console.log(n),d.push(n),console.log(d),g.innerHTML='<table class="record"></table>',console.log(g),S(d),console.log(r.currentTarget)}function S(r){console.log(r);for(let t=0;t<r.length;t++){let n=document.createElement("tr");n.id="text",n.className="note",n.innerHTML=`
    <td>${r[t].title}</td>     
    <td>${r[t].genre}</td>  
    <input name="del" type="button" value="видалити"/>`,document.querySelector(".record").appendChild(n),document.getElementsByName("del").forEach(function(e){e.addEventListener("click",function(){e.parentNode.parentNode.removeChild(e.parentNode)})}),document.getElementById("title").value=" ",document.getElementById("paging").value="0",console.log(r)}}
//# sourceMappingURL=page-2.js.map
